%YAML:1.0
---
Middle_Line:
        [
                { x: 4.0, y: -7.5, z: 0 },
                { x: 6.537, y: -7.5, z: 0 },
                { x: 10.0, y: -12.56, z: 0 },
                { x: 10.746, y: -12.56, z: 0 },
                { x: 17.254, y: -2.44, z: 0 },
                { x: 18.0, y: -2.44, z: 0 },
                { x: 21.463, y: -7.5, z: 0 },
                { x: 24.0, y: -7.5, z: 0 }
        ]
Left_Road:
        [
                { x: 10, y: -1.08, z: 0.2 },
                { x: 10, y: -0.06, z: 0.2 },
                { x: 10, y: -0.06, z: 1 },
                { x: 20, y: -0.06, z: 1 },
                { x: 20, y: -1.08, z: 1 },
                { x: 20, y: -1.08, z: 0.2 }
        ]
Right_Road:
        [
                { x: 16.167, y: -13.8595, z: 0.738 },
                { x: 13.281, y: -15, z: 0.2 },
                { x: 13.281, y: -13.86, z: 0.2 },
                { x: 14.93, y: -12.75, z: 0.153 }

        ]
Self_Ring_High:
        [
                { x: 8.967, y: -8.671, z: 0.738 },
                { x: 8.669, y: -8.244, z: 0.738 },
                { x: 8.669, y: -5.66, z: 0.738 },
                { x: 10.6, y: -2.9, z: 0.738 },
                { x: 13.3664, y: -2.458, z: 0.288 },
                { x: 12.075, y: -3.933, z: 0.738 },
                { x: 10.469, y: -6.228, z: 0.738 },
                { x: 10.469, y: -7.676, z: 0.738 },
                { x: 10.252, y: -10.505, z: 0.138 }
        ]
Enemy_Ring_High:
        [
                { x: 19.033, y: -6.329, z: 0.738 },
                { x: 19.331, y: -6.756, z: 0.738 },
                { x: 19.331, y: -9.34, z: 0.738 },
                { x: 16.167, y: -13.8595, z: 0.738 },
                { x: 14.93, y: -12.75, z: 0.153 },
                { x: 16.048, y: -11.153, z: 0.6 },
                { x: 17.68, y: -8.82, z: 0.6 },
                { x: 17.68, y: -7.276, z: 0.6 }
        ]
Enemy_Left_High:
        [
                { x: 25.075, y: -11.417, z: 0.4 },
                { x: 25.075, y: -15, z: 0.4 },
                { x: 20.778, y: -15, z: 0.4 },
                { x: 20.778, y: -13.86, z: 0.4 },
                { x: 22.488, y: -11.417, z: 0.4 }
        ]
Enemy_Right_High:
        [
                { x: 19.814, y: -2.69, z: 0.4 },
                { x: 19.814, y: -2.69, z: 1 },
                { x: 23.076, y: -2.69, z: 1 },
                { x: 23.076, y: -4.281, z: 1 },
                { x: 23.076, y: -4.281, z: 0.4 },
                { x: 20.829, y: -4.281, z: 0.4 }    
        ]
Enemy_Buff:
        [
                { x: 18.713, y: -2.54, z: 0.948 },
                { x: 18.713, y: -1.29, z: 0.948 },
                { x: 18.713, y: -1.29, z: 1.648 },
                { x: 21.426, y: -1.29, z: 1.648 },
                { x: 21.426, y: -2.54, z: 1.648 },
                { x: 21.426, y: -2.54, z: 0.948 }
        ]
